name: profocus
description: A productivity app with progress tracking, Pomodoro, and more.
version: 1.0.0

environment:
  sdk: ">=3.3.0 <4.0.0" # Updated to latest stable Flutter SDK range

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.1.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  firebase_database: ^11.1.4
  firebase_messaging: ^15.1.3
  cloud_functions: ^5.1.1
  provider: ^6.1.2
  flutter_local_notifications: ^17.2.3
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  share_plus: ^11.1.0
  pdf: ^3.11.0
  flutter_quill: ^9.2.3 # Updated to latest
  animations: ^2.0.11
  uuid: ^4.5.0
  dartz: ^0.10.1
  intl: ^0.20.2 # Matches flutter_quill requirement

flutter:
  uses-material-design: true

  assets:
    - assets/images/pomodoro_backgrounds/b1.jpg
    - assets/images/pomodoro_backgrounds/b2.jpg
    - assets/images/pomodoro_backgrounds/b3.jpg
    - assets/audio/pomodoro_music.mp3
